FROM node:14-alpine AS build
WORKDIR /app
COPY TheServerClient/ /app
RUN apk add curl \
    && curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz \
    && gunzip elm.gz \
    && chmod +x elm \
    && mv elm /usr/local/bin/
RUN elm make --optimize src/Main.elm --output dist/main.js

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html/
EXPOSE 80