version: '3.4'

services:
  theserver:
    image: ${DOCKER_REGISTRY-}theserver
    build:
      context: .
      dockerfile: TheServer/dockerfile
    ports:
      - '8181:80'
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
        
  theserverclient:
    image: ${DOCKER_REGISTRY-}theserverclient
    build:
      context: .
      dockerfile: TheServerClient/dockerfile
    ports:
      - '8182:80'
    depends_on:
      - theserver