version: '3'
services:
  app:
    container_name: docker-theserver-mongo
    restart: always
    build: .
    ports:
      - '8181:80'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'